apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cd-ripper.fullname" . }}
  labels:
    {{- include "cd-ripper.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cd-ripper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cd-ripper.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: cd-ripper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.privileged }}
          securityContext:
            privileged: true
          {{- end }}
          env:
            - name: CD_DEVICE
              value: {{ .Values.device | quote }}
          volumeMounts:
            - name: device
              mountPath: {{ .Values.device }}
            - name: udev
              mountPath: /run/udev
              readOnly: true
            - name: output
              mountPath: /root/Music
      volumes:
        - name: device
          hostPath:
            path: {{ .Values.device }}
            type: BlockDevice
        - name: udev
          hostPath:
            path: /run/udev
            type: Directory
        - name: output
          {{- if .Values.nfs.enabled }}
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
          {{- else }}
          hostPath:
            path: {{ .Values.outputPath }}
            type: DirectoryOrCreate
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
